hopefully better testing

diff --git a/.azure-pipelines/linux_build.yml b/.azure-pipelines/linux_build.yml
--- a/.azure-pipelines/linux_build.yml
+++ b/.azure-pipelines/linux_build.yml
@@ -61,7 +61,10 @@ steps:
     export RDBASE=`pwd`
     export PYTHONPATH=${RDBASE}:${PYTHONPATH}
     cd build
-    grep -q "RDK_BUILD_DESCRIPTORS3D:BOOL=ON" CMakeCache.txt
+    if ! grep -Fq "RDK_BUILD_DESCRIPTORS3D:BOOL=ON" CMakeCache.txt; then
+      echo "ERROR: Eigen support was not enabled in CMakeCache.txt"
+      exit 1
+    fi
 - bash: |
     source ${CONDA}/etc/profile.d/conda.sh
     conda activate rdkit_build
